name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Giving permission
        run: chmod +x gradlew
        
      - name: Checking for spotless
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    # container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Giving permission
        run: chmod +x gradlew

      - name: Check spotless
        run: ./gradlew spotlessCheck

      - name: Compile and run tests on robot code
        run: ./gradlew build
