name: 🐛 Bug Report
description: Report a bug
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: "Brief description of the issue"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: "What should have happened?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
      default: 1
    validations:
      required: true